// AUTO-GENERATED by tools/sync_build.py. Do not edit manually.
export const BUILD_INFO = Object.freeze({
  "product": "Submarine Commander WW2",
  "studio": "Vale Games",
  "version": "v2.0.0-alpha.30",
  "semver": "2.0.0-alpha.30",
  "buildId": "SCWW2-20260622-1810-BRT-F15-HIGH-COMMAND-ORDERS",
  "date": "2026-06-22",
  "time": "18:10",
  "timezone": "America/Sao_Paulo",
  "phase": "15",
  "phaseName": "Strategic High Command Orders",
  "channel": "alpha",
  "release": false,
  "qaStatus": "PASS",
  "saveSchemaVersion": 9,
  "notes": "Phase 15 adds national high command orders for Germany, United Kingdom and United States: one-time theater decisions, cost gating, mission requirements, persistent save effects, strategic assessment integration, mobile strategy panel, translations and automated validation while preserving all earlier systems."
});
