// AUTO-GENERATED by tools/sync_build.py. Do not edit manually.
export const BUILD_INFO = Object.freeze({
  "product": "Submarine Commander WW2",
  "studio": "Vale Games",
  "version": "2.2.0",
  "semver": "2.2.0",
  "buildId": "SCWW2-2.2.0-20260803-1919-BRT",
  "date": "2026-08-03",
  "time": "19:19",
  "timezone": "America/Sao_Paulo",
  "phase": "56",
  "phaseName": "Immersive Torpedo Combat Feedback",
  "channel": "stable",
  "release": true,
  "qaStatus": "PASS",
  "saveSchemaVersion": 40,
  "notes": "Stable mobile-first release with cinematic torpedo feedback, officer voice reports, richer synthesized naval effects, eliminated contact markers on the tactical chart, the guided combat tutorial and every existing character, avatar, vessel, campaign and simulation system preserved."
});
