#!/usr/bin/env python3
"""Synchronize every build/version surface from BUILD_INFO.json.

BUILD_INFO.json is the single source of truth. Run this script before every ZIP.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BUILD_PATH = ROOT / "BUILD_INFO.json"


def read_json(path: Path):
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def write_json(path: Path, data) -> None:
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def main() -> None:
    info = read_json(BUILD_PATH)
    required = {
        "product", "studio", "version", "semver", "buildId", "date", "time",
        "timezone", "phase", "phaseName", "channel", "release", "qaStatus",
        "saveSchemaVersion", "notes",
    }
    missing = sorted(required.difference(info))
    if missing:
        raise SystemExit(f"BUILD_INFO.json missing fields: {', '.join(missing)}")

    build_js = (
        "// AUTO-GENERATED by tools/sync_build.py. Do not edit manually.\n"
        f"export const BUILD_INFO = Object.freeze({json.dumps(info, ensure_ascii=False, indent=2)});\n"
    )
    (ROOT / "js" / "build.js").write_text(build_js, encoding="utf-8")

    index_path = ROOT / "index.html"
    index = index_path.read_text(encoding="utf-8")
    index = re.sub(
        r"<title>.*?</title>",
        f"<title>{info['product']} — {info['version']}</title>",
        index,
        count=1,
        flags=re.DOTALL,
    )
    index = re.sub(
        r'<meta name="description" content="[^"]*">',
        f'<meta name="description" content="{info["product"]} — simulador tático naval mobile-first da {info["studio"]}.">',
        index,
        count=1,
    )
    index_path.write_text(index, encoding="utf-8")

    manifest_path = ROOT / "manifest.json"
    manifest = read_json(manifest_path)
    manifest.update({
        "name": f"{info['product']} {info['version']}",
        "short_name": "Sub Commander",
        "description": f"{info['product']} — {info['version']} by {info['studio']}",
        "version": info["semver"],
    })
    write_json(manifest_path, manifest)

    sw_path = ROOT / "service-worker.js"
    sw = sw_path.read_text(encoding="utf-8")
    sw = re.sub(
        r"const CACHE_VERSION = '[^']+';",
        f"const CACHE_VERSION = '{info['semver']}-{info['date'].replace('-', '')}-{info['time'].replace(':', '')}';",
        sw,
        count=1,
    )
    sw_path.write_text(sw, encoding="utf-8")

    print(f"Build synchronized: {info['version']} / {info['buildId']} / QA {info['qaStatus']}")


if __name__ == "__main__":
    main()
